name: TotalFreedomMod
main: me.totalfreedom.totalfreedommod.TotalFreedomMod
version: ${project.version}
description: Plugin for the Total Freedom server.
softdepend:
  - BukkitTelnet
  - Essentials
  - CoreProtect
  - LibsDisguises
  - WorldEdit
  - WorldGuard
  - WorldGuardExtraFlags
  - JDA
  - Votifier
authors: [Madgeek1450, Prozza]
api-version: "1.17"
libraries:
  - commons-io:commons-io:2.11.0
  - org.apache.commons:commons-lang3:3.12.0